// user
const USERINFO = "USERINFO";
const USERSIGNIN = "USERSIGNIN";
const USERSIGNUP = "USERSIGNUP";

// home
const HOME = "HOME";

//APP
const AUTH = "AUTH";
const APP = "APP";

// AuthLoading
const AUTHLOADING = "AUTHLOADING";

export { HOME, USERINFO, USERSIGNIN, USERSIGNUP, AUTH, APP, AUTHLOADING};

