// LOGIN
export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNIN_SUCCEEDED = "FETCH_SIGNIN_SUCCEEDED";
export const FETCH_SIGNIN_FAILED = "FETCH_SIGNIN_FAILED";
export const LOGINSUCCEEDED = "LOGINSUCCEEDED";
// LOGOUT
export const FETCH_LOGOUT = "FETCH_LOGOUT";
export const FETCH_LOGOUT_SUCCEEDED = "FETCH_LOGOUT_SUCCEEDED";
export const LOGOUTSUCCEEDED = "LOGOUTSUCCEEDED";

// SIGNUP
export const FETCH_SIGNUP = "FETCH_SIGNUP";
export const FETCH_SIGNUP_SUCCEEDED = "FETCH_SIGNUP_SUCCEEDED";
export const FETCH_SIGNUP_FAILED = "FETCH_SIGNUP_FAILED";

//INFO
export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCEEDED = "FETCH_USER_INFO_SUCCEEDED";
export const FETCH_USER_INFO_FAILED = "FETCH_USER_INFO_FAILED";




